name: TagsX
version: ${version}
description: ${description}
main: pl.syntaxdevteam.tagsx.TagsX
api-version: '1.21'
authors: [ SyntaxDevTeam ]
website: https://syntaxdevteam.pl

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    VaultUnlocked:
      load: BEFORE
      required: false