name: TagsX
version: ${version}
description: ${description}

api-version: '1.21'
authors: [ SyntaxDevTeam ]
website: https://syntaxdevteam.pl

main: pl.syntaxdevteam.tagsx.TagsX
loader: pl.syntaxdevteam.tagsx.loader.SyntaxLoader
has-open-classloader: false

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    VaultUnlocked:
      load: BEFORE
      required: false